[env:esp32-c6-devkitm-1]
; On force l'utilisation d'une plateforme qui intègre Arduino 3.x
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200

; Ces deux lignes sont cruciales pour les ESP32-C6 ! 
; Elles forcent l'affichage du Serial Monitor sur le port USB natif de la puce.
build_flags = 
    -D ARDUINO_USB_MODE=1 
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
    adafruit/Adafruit PN532 @ ^1.3.0

monitor_dtr = 0
monitor_rts = 0